// <auto-generated />
using System;
using BetaCinema.Persistence.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BetaCinema.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260419031902_updatediscussion")]
    partial class updatediscussion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BetaCinema.Domain.Entities.Banner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Banners");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Carts.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsActive");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Carts.CartFoodItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FoodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("FoodId");

                    b.ToTable("CartFoodItems");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Discussions.MovieReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AngryCount")
                        .HasColumnType("int");

                    b.Property<int>("CommentCount")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("HahaCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsSpoiler")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerifiedPurchase")
                        .HasColumnType("bit");

                    b.Property<int>("LikeCount")
                        .HasColumnType("int");

                    b.Property<int>("LoveCount")
                        .HasColumnType("int");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("ReactionCount")
                        .HasColumnType("int");

                    b.Property<int>("SadCount")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("WowCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "MovieId")
                        .IsUnique()
                        .HasFilter("[DeleteAt] IS NULL");

                    b.HasIndex("UserId", "Status");

                    b.HasIndex("MovieId", "Status", "CreateAt");

                    b.ToTable("MovieReviews", t =>
                        {
                            t.HasCheckConstraint("CK_MovieReviews_Rating", "[Rating] IS NULL OR [Rating] BETWEEN 1 AND 10");
                        });
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Discussions.Reaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CommentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReactionType")
                        .HasColumnType("int");

                    b.Property<Guid?>("ReviewId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CommentId", "ReactionType");

                    b.HasIndex("ReviewId", "ReactionType");

                    b.HasIndex("UserId", "CommentId")
                        .IsUnique()
                        .HasFilter("[CommentId] IS NOT NULL");

                    b.HasIndex("UserId", "ReviewId")
                        .IsUnique()
                        .HasFilter("[ReviewId] IS NOT NULL");

                    b.ToTable("Reactions", t =>
                        {
                            t.HasCheckConstraint("CK_Reactions_Target_OnlyOne", "(([ReviewId] IS NOT NULL AND [CommentId] IS NULL) OR ([ReviewId] IS NULL AND [CommentId] IS NOT NULL))");
                        });
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Discussions.ReviewComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AngryCount")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Depth")
                        .HasColumnType("int");

                    b.Property<int>("HahaCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("bit");

                    b.Property<int>("LikeCount")
                        .HasColumnType("int");

                    b.Property<int>("LoveCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("MentionUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReactionCount")
                        .HasColumnType("int");

                    b.Property<int>("ReplyCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("ReplyToCommentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReviewId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RootCommentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SadCount")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("WowCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MentionUserId");

                    b.HasIndex("ReplyToCommentId");

                    b.HasIndex("UserId", "CreatedAt");

                    b.HasIndex("ParentCommentId", "Status", "CreatedAt");

                    b.HasIndex("RootCommentId", "Status", "CreatedAt");

                    b.HasIndex("ReviewId", "Depth", "Status", "CreatedAt");

                    b.ToTable("ReviewComments", t =>
                        {
                            t.HasCheckConstraint("CK_ReviewComments_Depth", "[Depth] IN (0,1,2)");

                            t.HasCheckConstraint("CK_ReviewComments_Depth_Relation", "([Depth] = 0 AND [ParentCommentId] IS NULL AND [RootCommentId] IS NULL AND [ReplyToCommentId] IS NULL) OR ([Depth] IN (1,2) AND [ParentCommentId] IS NOT NULL AND [RootCommentId] IS NOT NULL AND [ReplyToCommentId] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Foods.Food", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.GeneralSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BreakTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BussinessHour")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CloseTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("GeneralSettings");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AudienceType")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DispatchStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpireAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NotificationType")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Notifications.UserNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId");

                    b.HasIndex("UserId", "IsRead");

                    b.HasIndex("UserId", "NotificationId")
                        .IsUnique();

                    b.ToTable("UserNotifications");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Orders.Bill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BillStatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ExpireAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaymentAttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("PaymentGatewayTransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PaymentMethodId")
                        .HasColumnType("int");

                    b.Property<decimal?>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalMoney")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TradingCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BillStatusId");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("UserId");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Orders.BillFood", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FoodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.HasIndex("FoodId");

                    b.ToTable("BillFoods");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Orders.BillPromotion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PromotionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PromotionId");

                    b.HasIndex("BillId", "PromotionId")
                        .IsUnique();

                    b.ToTable("BillPromotions");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Orders.BillStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("BillStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "PendingPayment",
                            StatusName = "Đang chờ thanh toán"
                        },
                        new
                        {
                            Id = 2,
                            Code = "Paid",
                            StatusName = "Đã thanh toán"
                        },
                        new
                        {
                            Id = 3,
                            Code = "CancelledByUser",
                            StatusName = "Đã hủy bởi người dùng"
                        },
                        new
                        {
                            Id = 4,
                            Code = "Expired",
                            StatusName = "Đã hết hạn"
                        },
                        new
                        {
                            Id = 5,
                            Code = "Failed",
                            StatusName = "Thanh toán thất bại"
                        },
                        new
                        {
                            Id = 6,
                            Code = "Refunded",
                            StatusName = "Đã hoàn tiền"
                        },
                        new
                        {
                            Id = 7,
                            Code = "ReconciliationFailed",
                            StatusName = "Đối soát thất bại"
                        });
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Orders.BillTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.HasIndex("TicketId");

                    b.ToTable("BillTickets");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Orders.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("ExpirationTimeInMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MethodCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MethodCode")
                        .IsUnique();

                    b.ToTable("PaymentMethods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = false,
                            MethodCode = "CASH",
                            MethodName = "Thanh toán tại quầy"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = false,
                            MethodCode = "VNPAY",
                            MethodName = "Thanh toán qua VNPAY"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = false,
                            MethodCode = "MOMO",
                            MethodName = "Thanh toán qua Ví MoMo"
                        });
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Orders.PriceRuleType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PriorityValue")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PriceRuleTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Quy tắc chung Ngày thường",
                            PriorityValue = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Quy tắc chung Cuối tuần",
                            PriorityValue = 0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Khung Giờ Vàng",
                            PriorityValue = 10
                        },
                        new
                        {
                            Id = 4,
                            Name = "Thứ Ba Vui Vẻ",
                            PriorityValue = 20
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sự kiện/Ngày Lễ",
                            PriorityValue = 100
                        });
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Orders.PriceTier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AdjustmentType")
                        .HasColumnType("int");

                    b.Property<decimal>("AdjustmentValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("ApplicableDate")
                        .HasColumnType("date");

                    b.Property<int?>("ApplicableDay")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndAt")
                        .HasColumnType("time");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PriceRuleTypeId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartAt")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("PriceRuleTypeId");

                    b.ToTable("PriceTiers");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Orders.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("PriceTicket")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("SeatId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Promotions.Promotion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentUsage")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiscountType")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MaxDiscountValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MinBillValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RankCustomerId")
                        .HasColumnType("int");

                    b.Property<int>("Scope")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsageLimit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RankCustomerId");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Seats.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Line")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SeatStatusId")
                        .HasColumnType("int");

                    b.Property<int>("SeatTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("SeatStatusId");

                    b.HasIndex("SeatTypeId");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Seats.SeatStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SeatStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "AVAILABLE",
                            NameStatus = "Còn trống"
                        },
                        new
                        {
                            Id = 2,
                            Code = "HELD",
                            NameStatus = "Đang giữ"
                        },
                        new
                        {
                            Id = 3,
                            Code = "BOOKED",
                            NameStatus = "Đã bán"
                        });
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Seats.SeatType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NameType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Surcharge")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("SeatTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NameType = "Standard",
                            Surcharge = 0m
                        },
                        new
                        {
                            Id = 2,
                            NameType = "VIP",
                            Surcharge = 20000m
                        },
                        new
                        {
                            Id = 3,
                            NameType = "Sweetbox",
                            Surcharge = 50000m
                        });
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.ShowTimes.Cinema", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cinemas");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.ShowTimes.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Director")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MovieDuration")
                        .HasColumnType("int");

                    b.Property<Guid>("MovieTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PremiereDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RateId")
                        .HasColumnType("int");

                    b.Property<string>("Trailer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MovieTypeId");

                    b.HasIndex("RateId");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.ShowTimes.MovieType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MovieTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MovieTypes");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.ShowTimes.Rate", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Rates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "P",
                            Description = "Phim được phép phổ biến rộng rãi đến mọi đối tượng.",
                            Name = "Mọi lứa tuổi"
                        },
                        new
                        {
                            Id = 2,
                            Code = "C13",
                            Description = "Phim cấm khán giả dưới 13 tuổi.",
                            Name = "Cấm trẻ em dưới 13 tuổi"
                        },
                        new
                        {
                            Id = 3,
                            Code = "C16",
                            Description = "Phim cấm khán giả dưới 16 tuổi.",
                            Name = "Cấm trẻ em dưới 16 tuổi"
                        },
                        new
                        {
                            Id = 4,
                            Code = "C18",
                            Description = "Phim cấm khán giả dưới 18 tuổi.",
                            Name = "Cấm trẻ em dưới 18 tuổi"
                        });
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.ShowTimes.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<Guid>("CinemaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CinemaId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.ShowTimes.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("RoomId", "StartAt")
                        .IsUnique();

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.ShowTimes.WatchList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "MovieId")
                        .IsUnique()
                        .HasDatabaseName("UX_Watchlists_UserId_MovieId");

                    b.ToTable("WatchLists");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Users.ConfirmEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConfirmCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiredTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsConfirm")
                        .HasColumnType("bit");

                    b.Property<int>("Purpose")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ConfirmEmails");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Users.ExternalLogin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ExternalLogins");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Users.RankCustomer", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MinimumPoint")
                        .HasColumnType("int");

                    b.Property<string>("RankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RankName")
                        .IsUnique();

                    b.ToTable("RankCustomers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            MinimumPoint = 0,
                            RankName = "Standard"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            MinimumPoint = 200000,
                            RankName = "Silver"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            MinimumPoint = 500000,
                            RankName = "Gold"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            MinimumPoint = 1000000,
                            RankName = "Platinum"
                        });
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Users.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiredTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Users.Role", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "Staff"
                        },
                        new
                        {
                            Id = 3,
                            RoleName = "Member"
                        });
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Point")
                        .HasColumnType("int");

                    b.Property<int>("RankCustomerId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserStatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NumberPhone")
                        .IsUnique();

                    b.HasIndex("RankCustomerId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasFilter("[UserName] IS NOT NULL");

                    b.HasIndex("UserStatusId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Users.UserPromotion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("PromotionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PromotionId");

                    b.HasIndex("UserId", "PromotionId")
                        .IsUnique();

                    b.ToTable("UserPromotions");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Users.UserStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("StatusName")
                        .IsUnique();

                    b.ToTable("UserStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            StatusName = "Chờ kích hoạt"
                        },
                        new
                        {
                            Id = 2,
                            StatusName = "Đang hoạt động"
                        },
                        new
                        {
                            Id = 3,
                            StatusName = "Đã khóa"
                        },
                        new
                        {
                            Id = 4,
                            StatusName = "Đã cấm"
                        },
                        new
                        {
                            Id = 5,
                            StatusName = "Đã vô hiệu hóa"
                        });
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Carts.Cart", b =>
                {
                    b.HasOne("BetaCinema.Domain.Entities.Users.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Carts.CartFoodItem", b =>
                {
                    b.HasOne("BetaCinema.Domain.Entities.Carts.Cart", "Cart")
                        .WithMany("CartFoodItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BetaCinema.Domain.Entities.Foods.Food", "Food")
                        .WithMany("CartFoodItems")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Food");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Discussions.MovieReview", b =>
                {
                    b.HasOne("BetaCinema.Domain.Entities.ShowTimes.Movie", "Movie")
                        .WithMany("MovieReviews")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BetaCinema.Domain.Entities.Users.User", "User")
                        .WithMany("MovieReviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Discussions.Reaction", b =>
                {
                    b.HasOne("BetaCinema.Domain.Entities.Discussions.ReviewComment", "Comment")
                        .WithMany("Reactions")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BetaCinema.Domain.Entities.Discussions.MovieReview", "Review")
                        .WithMany("Reactions")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BetaCinema.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("Review");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Discussions.ReviewComment", b =>
                {
                    b.HasOne("BetaCinema.Domain.Entities.Users.User", "MentionUser")
                        .WithMany("MentionedInReviewComments")
                        .HasForeignKey("MentionUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BetaCinema.Domain.Entities.Discussions.ReviewComment", "ParentComment")
                        .WithMany("ChildComments")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BetaCinema.Domain.Entities.Discussions.ReviewComment", "ReplyToComment")
                        .WithMany("ReplyReferences")
                        .HasForeignKey("ReplyToCommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BetaCinema.Domain.Entities.Discussions.MovieReview", "Review")
                        .WithMany("Comments")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BetaCinema.Domain.Entities.Discussions.ReviewComment", "RootComment")
                        .WithMany("RootComments")
                        .HasForeignKey("RootCommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BetaCinema.Domain.Entities.Users.User", "User")
                        .WithMany("ReviewComments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MentionUser");

                    b.Navigation("ParentComment");

                    b.Navigation("ReplyToComment");

                    b.Navigation("Review");

                    b.Navigation("RootComment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Notifications.UserNotification", b =>
                {
                    b.HasOne("BetaCinema.Domain.Entities.Notifications.Notification", "Notification")
                        .WithMany("UserNotifications")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BetaCinema.Domain.Entities.Users.User", "User")
                        .WithMany("UserNotifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Notification");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Orders.Bill", b =>
                {
                    b.HasOne("BetaCinema.Domain.Entities.Orders.BillStatus", "BillStatus")
                        .WithMany("Bills")
                        .HasForeignKey("BillStatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BetaCinema.Domain.Entities.Orders.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId");

                    b.HasOne("BetaCinema.Domain.Entities.Users.User", "User")
                        .WithMany("Bills")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BillStatus");

                    b.Navigation("PaymentMethod");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Orders.BillFood", b =>
                {
                    b.HasOne("BetaCinema.Domain.Entities.Orders.Bill", "Bill")
                        .WithMany("BillFoods")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BetaCinema.Domain.Entities.Foods.Food", "Food")
                        .WithMany("BillFoods")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("Food");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Orders.BillPromotion", b =>
                {
                    b.HasOne("BetaCinema.Domain.Entities.Orders.Bill", "Bill")
                        .WithMany("BillPromotions")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BetaCinema.Domain.Entities.Promotions.Promotion", "Promotion")
                        .WithMany("BillPromotions")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Orders.BillTicket", b =>
                {
                    b.HasOne("BetaCinema.Domain.Entities.Orders.Bill", "Bill")
                        .WithMany("BillTickets")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BetaCinema.Domain.Entities.Orders.Ticket", "Ticket")
                        .WithMany("BillTickets")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Orders.PriceTier", b =>
                {
                    b.HasOne("BetaCinema.Domain.Entities.Orders.PriceRuleType", "PriceRuleType")
                        .WithMany("PriceTiers")
                        .HasForeignKey("PriceRuleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PriceRuleType");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Orders.Ticket", b =>
                {
                    b.HasOne("BetaCinema.Domain.Entities.ShowTimes.Schedule", "Schedule")
                        .WithMany("Tickets")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BetaCinema.Domain.Entities.Seats.Seat", "Seat")
                        .WithMany("Tickets")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Schedule");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Promotions.Promotion", b =>
                {
                    b.HasOne("BetaCinema.Domain.Entities.Users.RankCustomer", "RankCustomer")
                        .WithMany("Promotions")
                        .HasForeignKey("RankCustomerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("RankCustomer");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Seats.Seat", b =>
                {
                    b.HasOne("BetaCinema.Domain.Entities.ShowTimes.Room", "Room")
                        .WithMany("Seats")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BetaCinema.Domain.Entities.Seats.SeatStatus", "SeatStatus")
                        .WithMany("Seats")
                        .HasForeignKey("SeatStatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BetaCinema.Domain.Entities.Seats.SeatType", "SeatType")
                        .WithMany("Seats")
                        .HasForeignKey("SeatTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("SeatStatus");

                    b.Navigation("SeatType");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.ShowTimes.Movie", b =>
                {
                    b.HasOne("BetaCinema.Domain.Entities.ShowTimes.MovieType", "MovieType")
                        .WithMany("Movies")
                        .HasForeignKey("MovieTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BetaCinema.Domain.Entities.ShowTimes.Rate", "Rate")
                        .WithMany("Movies")
                        .HasForeignKey("RateId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("MovieType");

                    b.Navigation("Rate");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.ShowTimes.Room", b =>
                {
                    b.HasOne("BetaCinema.Domain.Entities.ShowTimes.Cinema", "Cinema")
                        .WithMany("Rooms")
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cinema");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.ShowTimes.Schedule", b =>
                {
                    b.HasOne("BetaCinema.Domain.Entities.ShowTimes.Movie", "Movie")
                        .WithMany("Schedules")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BetaCinema.Domain.Entities.ShowTimes.Room", "Room")
                        .WithMany("Schedules")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.ShowTimes.WatchList", b =>
                {
                    b.HasOne("BetaCinema.Domain.Entities.ShowTimes.Movie", "Movie")
                        .WithMany("WatchLists")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BetaCinema.Domain.Entities.Users.User", "User")
                        .WithMany("WatchLists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Users.ConfirmEmail", b =>
                {
                    b.HasOne("BetaCinema.Domain.Entities.Users.User", "User")
                        .WithMany("ConfirmEmails")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Users.ExternalLogin", b =>
                {
                    b.HasOne("BetaCinema.Domain.Entities.Users.User", "User")
                        .WithMany("ExternalLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Users.RefreshToken", b =>
                {
                    b.HasOne("BetaCinema.Domain.Entities.Users.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Users.User", b =>
                {
                    b.HasOne("BetaCinema.Domain.Entities.Users.RankCustomer", "RankCustomer")
                        .WithMany("Users")
                        .HasForeignKey("RankCustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BetaCinema.Domain.Entities.Users.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BetaCinema.Domain.Entities.Users.UserStatus", "UserStatus")
                        .WithMany("Users")
                        .HasForeignKey("UserStatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("RankCustomer");

                    b.Navigation("Role");

                    b.Navigation("UserStatus");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Users.UserPromotion", b =>
                {
                    b.HasOne("BetaCinema.Domain.Entities.Promotions.Promotion", "Promotion")
                        .WithMany("UserPromotions")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BetaCinema.Domain.Entities.Users.User", "User")
                        .WithMany("UserPromotions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Promotion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Carts.Cart", b =>
                {
                    b.Navigation("CartFoodItems");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Discussions.MovieReview", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Discussions.ReviewComment", b =>
                {
                    b.Navigation("ChildComments");

                    b.Navigation("Reactions");

                    b.Navigation("ReplyReferences");

                    b.Navigation("RootComments");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Foods.Food", b =>
                {
                    b.Navigation("BillFoods");

                    b.Navigation("CartFoodItems");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Notifications.Notification", b =>
                {
                    b.Navigation("UserNotifications");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Orders.Bill", b =>
                {
                    b.Navigation("BillFoods");

                    b.Navigation("BillPromotions");

                    b.Navigation("BillTickets");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Orders.BillStatus", b =>
                {
                    b.Navigation("Bills");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Orders.PriceRuleType", b =>
                {
                    b.Navigation("PriceTiers");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Orders.Ticket", b =>
                {
                    b.Navigation("BillTickets");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Promotions.Promotion", b =>
                {
                    b.Navigation("BillPromotions");

                    b.Navigation("UserPromotions");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Seats.Seat", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Seats.SeatStatus", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Seats.SeatType", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.ShowTimes.Cinema", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.ShowTimes.Movie", b =>
                {
                    b.Navigation("MovieReviews");

                    b.Navigation("Schedules");

                    b.Navigation("WatchLists");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.ShowTimes.MovieType", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.ShowTimes.Rate", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.ShowTimes.Room", b =>
                {
                    b.Navigation("Schedules");

                    b.Navigation("Seats");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.ShowTimes.Schedule", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Users.RankCustomer", b =>
                {
                    b.Navigation("Promotions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Users.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Users.User", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("Carts");

                    b.Navigation("ConfirmEmails");

                    b.Navigation("ExternalLogins");

                    b.Navigation("MentionedInReviewComments");

                    b.Navigation("MovieReviews");

                    b.Navigation("RefreshTokens");

                    b.Navigation("ReviewComments");

                    b.Navigation("UserNotifications");

                    b.Navigation("UserPromotions");

                    b.Navigation("WatchLists");
                });

            modelBuilder.Entity("BetaCinema.Domain.Entities.Users.UserStatus", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
